version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo installing source NPM dependencies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - npm run build
      
artifacts:
  files:
    - '**/*'


 
